### PR TITLE
Feat/automatic extraction and compilation with formatjs

### PR DESCRIPTION
**Pull request by abderrahmaneMustapha**
# Description
automatic extraction  of messages  and compilation with formatjs, combined with react int, and react intl  translation manager 
without overwriting the existing translated file. 

## Type of change
- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by abderrahmaneMustapha** [comment]
@ZibanPirate & @Omar-Belghaouti  i can not understand why the checks is failing here ??

**Comment by Omar-Belghaouti** [comment]
@abderrahmaneMustapha is this branch up-to-date with main? You can also check the logs for the testing

**Comment by ZibanPirate** [comment]
hey @abderrahmaneMustapha , the tests were failing because of recent changes we merged to main, i fixed it in #397 and rebased `feat/localization`.

Now you have to rebase your branch `feat/automatic-extraction-and-compilation-with-formatjs` on `feat/localization`, to do that:

1. delete `feat/localization` and checkout to it again (because it's rebased)
```sh
git branch -D feat/localization
git checkout feat/localization
```

2. checkout to your branch and rebase on `feat/localization` :
```sh
git checkout feat/automatic-extraction-and-compilation-with-formatjs
git rebase feat/localization
```
3. you will see a conflict in the file `web/src/localization/index.tsx`, just:
  - Go to that file
  - Click on "Accept Current Changes"
  - Save the file
  - Stage the file, by going to the "Git tab" of VSCode and clicking the `+` beside the file name
  - finally run `git rebase --continue`

4. force push your changes:
```sh
git push -f
```

once this is done, we will review the changes in the PR, there are some comments i wanna add

**Comment by abderrahmaneMustapha** [comment]
@ZibanPirate @Omar-Belghaouti , @dzcode-io/members ready for reviews , i also fixed the the failing test in the faq page test because of the missing int provider.

**Pull request merged**
