### PR TITLE
Feature: Mobile code base

### PR DESCRIPTION
**Pull request by ZibanPirate**
# Description

mobile app feature branch

_please branch out of [`feature/mobile-code-base`](https://github.com/dzcode-io/dzcode.io/tree/feature/mobile-code-base) for any changes related to mobile code implementation_

## Tasks

- [x] Initiate React Native code base under folder `mobile` ( #320 #323  )
- [x] setup CI/CD pipelines to run checks for PRs ( #324 )
- [x] Implementing the project's structure ( #325 )

## Type of change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by Omar-Belghaouti — COMMENTED** [review]
@ZibanPirate I will start by implementing the project's structure

**Comment by ZibanPirate** [comment]
i will setup CI/CD checks for PRs

**Review by Omar-Belghaouti — CHANGES_REQUESTED** [review]
@ZibanPirate there is a conflict in yarn.lock that need to be checked

**Comment by ZibanPirate** [comment]
@Omar-Belghaouti i rebased from `main`, now this branch is up-to-date and the conflict is resolved, 

Now that we have a stable code (kinda), we can now merge this PR to `main` and start actually working on the `mobile` code as part of dzcode.io, and create PRs that targets `main` branch directly

**Review by Omar-Belghaouti — APPROVED** [review]

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate sounds awesome 😁

**Pull request merged**
