### PR TITLE
add react-native-help-create project 🐱‍👤

### PR DESCRIPTION
**Pull request by Omar-Belghaouti**
# Description

Hi again 😊! I am happy to add another open source project that I believe it will help mobile developers (especially react native developer 😁)

### CODE REVIEW

**Review by ZibanPirate — APPROVED** [review]
Thank you @Omar-Belghaouti for adding another awesome project!

**Review by ZibanPirate — CHANGES_REQUESTED** [review]
one thing before we merge @Omar-Belghaouti , please rename
`data/models/projects/React_Native_Help_Create/info.js`
to
`data/models/projects/React_Native_Help_Create/info.json`

**Comment by Omar-Belghaouti** [comment]
> one thing before we merge @Omar-Belghaouti , please rename
> `data/models/projects/React_Native_Help_Create/info.js`
> to
> `data/models/projects/React_Native_Help_Create/info.json`

Oh my bad! 😅 I'll work on it

**Review by ZibanPirate — APPROVED** [review]
all good 👌🏼 thanks again for the project !

**Comment by Omar-Belghaouti** [comment]
> all good 👌🏼 thanks again for the project !

You're welcome!

**Pull request merged**
