### PR TITLE
Initializing project's structure

### PR DESCRIPTION
**Pull request by Omar-Belghaouti**
# Description

Implementing the mobile project's structure.

## Type of change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by ZibanPirate — CHANGES_REQUESTED** [review]
hey while you're at it, i think we should ignore `./android` and `./ios` folders, that's the whole point of expo, so for any body who want's to run it on a emulator, just build it on his machine only, no need to commit that code that **only** runs on his machine.

**Comment by Omar-Belghaouti** [comment]
> hey while you're at it, i think we should ignore `./android` and `./ios` folders, that's the whole point of expo, so for any body who want's to run it on a emulator, just build it on his machine only, no need to commit that code that **only** runs on his machine.

Okay, but are we gonna need any native functions in the future, because sometimes we need some native implementations and call them using react native bridges. For now I will add them to .gitignore file but if we face that problem I will remove them from .gitignore

**Review by ZibanPirate — CHANGES_REQUESTED** [review]
heyy @Omar-Belghaouti one quick fix, we really don't want to push native code at all, as you can see here, the code is pushed, and after that you added them to `.gitignore`, now they will stay like that forever haha, no worries it's an easy fix:

just delete the folder `android`, commit then push the changes, once pushed, you can then restore it from your bin recycler, and continue what you're doing like nothing happened

**Comment by Omar-Belghaouti** [comment]
> heyy @Omar-Belghaouti one quick fix, we really don't want to push native code at all, as you can see here, the code is pushed, and after that you added them to `.gitignore`, now they will stay like that forever haha, no worries it's an easy fix:
> 
> just delete the folder `android`, commit then push the changes, once pushed, you can then restore it from your bin recycler, and continue what you're doing like nothing happened

@ZibanPirate okay, I will do it right now, however when I saw the latest commit here on GitHub those folders does not exist!

**Review by ZibanPirate — APPROVED** [review]
great thanks @Omar-Belghaouti !!

**Comment by Omar-Belghaouti** [comment]
#319

**Pull request merged**
