### PR TITLE
delete server code on data and clear cloud resources

### PR DESCRIPTION
**Pull request by ZibanPirate**
- to #572 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (changes that require a fresh clone of the repo)
- [x] I'm not sure

### CODE REVIEW

**Comment by omdxp** [comment]
the new PR template is a bit ambiguous, don't you think?

It shows how many tasks are left

**Review by omdxp — APPROVED** [review]

**Comment by ZibanPirate** [comment]
> the new PR template is a bit ambiguous, don't you think?
> 
> 
> 
> It shows how many tasks are left

Yup you're right, GitHub is currently working on a fix [here](https://github.com/orgs/community/discussions/5238) but they don't have any ETA yet, what's your suggestion in the meantime? Should we use it like the old way?

**Comment by omdxp** [comment]
> Yup you're right, GitHub is currently working on a fix [here](https://github.com/orgs/community/discussions/5238) but they don't have any ETA yet, what's your suggestion in the meantime? Should we use it like the old way?

It seems that they are working on it from a long time ago..

My suggestion is to use more dynamic template using YAML syntax with an option selector like this one [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms):

Screenshot 2023-04-11 at 5 11 47 AM

**Comment by ZibanPirate** [comment]
> My suggestion is to use more dynamic template using YAML syntax with an option selector like this one [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms):

That only works for issues, doesn't work for PRs unfortunately

**Pull request merged**
