### PR TITLE
request to add a dart package

### PR DESCRIPTION
**Pull request by dfourcfive**
request to add dzair_data_usage 

dzair_data_usage  is a dart/flutter package for dealing with algerian cities data such as dairas,communes and more.

https://github.com/dfourcfive/dzair_data_usage

### CODE REVIEW

**Comment by Omar-Belghaouti** [comment]
@dfourcfive do you have any social handles?

**Review by ZibanPirate — CHANGES_REQUESTED** [review]
hey @dfourcfive thanks for submitting your project.

can you please run:

```sh
yarn
```
then
```sh
yarn lint:fix
```

then commit your changes and push them, this will fix linting errors and make the checks pass

**Comment by dfourcfive** [comment]
@Omar-Belghaouti  not quite sure if i do cover every social media with same username , but i do have facebook if it fits the job

**Comment by Omar-Belghaouti** [comment]
@dfourcfive yeah, I would like to contact you, what's your fb?

**Review by ZibanPirate — APPROVED** [review]
Look good 👌🏽, merging

**Pull request merged**
