### PR TITLE
FIX: Mobile Filter Contribute Component Lag 

### LINKED ISSUE #375: Mobile `Filter` component in `Contribute` screen is laggy
**Describe the bug**
When we have many contributions cards (>10), the filter component starts to lag

**To Reproduce**

1. Open dzcode mobile app
2. Navigate to `Contribute` screen
3. Open the filter component
4. See that it lags when trying to open/close it
5. It also lags when you try to select any filter option.

**Expected behavior**
It should behave instant and smooth.

**Environment:**

- OS: iOS 15.0
- Browser : Native Mobile App
- Version: latest version as of writing this issue.

**Additional context**

This is most because, whenever we change the filter options, we trigger a re-render of the whole Contribute screen, including all the contributions cards, you will notice that it's faster if you have fewer contribution cards.

Also, this is even slower on my low-end Android device.

### LINKED ISSUE #404: Error: Could not open URL `'/Learn/About_dzcode_io/Add_Your_Article_To_dzcode_io'`: No Activity found to h...
Sentry Issue: [MOBILE-1D](https://sentry.io/organizations/dzcode/issues/2689975635/?referrer=github_integration)

```
Error: Could not open URL '/Learn/About_dzcode_io/Add_Your_Article_To_dzcode_io': No Activity found to handle Intent { act=android.intent.action.VIEW dat=/Learn/About_dzcode_io/Add_Your_Article_To_dzcode_io flg=0x10000000 }
  at None (app:///index.android.bundle:26:1113)
  at default (app:///index.android.bundle:1043:163)
  at onPress (app:///index.android.bundle:1044:4827)
  at touchableHandlePress (app:///index.android.bundle:219:3902)
  at _performSideEffectsForTransition (app:///index.android.bundle:225:9661)
...
(23 additional frame(s) were not displayed)
```

### LINKED ISSUE #405: Error: Unable to open URL: file:///learn/git_basics/pull_merge_request
Sentry Issue: [MOBILE-1C](https://sentry.io/organizations/dzcode/issues/2687237953/?referrer=github_integration)

```
Error: Unable to open URL: file:///learn/git_basics/pull_merge_request
  at None (app:///main.jsbundle:26:1113)
  at None (app:///main.jsbundle:1043:192)
  at onPress (app:///main.jsbundle:1044:4827)
  at None (app:///main.jsbundle:219:3902)
  at _performSideEffectsForTransition (app:///main.jsbundle:225:9690)
...
(23 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Omar-Belghaouti**
# Description

This PR is dedicated to fix the lag for the filter component when refreshing contributions. It is also dedicated to fix some Sentry errors.

Fixes #375
Fixes #404
Fixes #405 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by ZibanPirate — CHANGES_REQUESTED** [review]
hey @Omar-Belghaouti thanks for the suggested changes!

let's clear it a bit by removing all the unwanted changes in this PR :
```sh
git reset HEAD~

git reset --hard

git reset HEAD~

yarn

yarn rimraf **/src/_common

yarn lerna run lint:prettier -- -- --write .

git add .

git commit -m "showing loader in filter component when refreshing"

```

then will give it a good review 👌🏽

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate as for those Sentry related errors, I have tried their use cases and nothing happened, I believe those were existed during the dev process.

**Comment by Omar-Belghaouti** [comment]
This is still a WIP, trying some hacks with memoizing components, if it will not help I'll normalize the redux state.

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate So I am doing the redux state normalization so the data can be selected the same way as in the database, this approach is way better than storing an array of objects (this method is suggested for all kind of states that are stored in redux as it is shown [here](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape)).

The idea is to store for example the `contributions` array as an object instead containing the `byId` and `allIds` properties:
```js
contributions: {
  byId: {
    1: {},
    2: {},
    ...
  },
  allIds: [1, 2, ...]
}
```
So when selecting all the contributions we can use something like this:
```ts
const selectContributions = (state: StateInterface) =>
  state.contributeScreen.contributions.allIds.map(
    (id) => state.contributeScreen.contributions.byId[id]
  );
```
As you can see, now selecting an item would be much performant and it will not get out of sync, because the state is stored in a map of ids as keys and contributions as values. This can help the rendering process much efficient as it will not update all state but only the ones that are needed to be so not all components will re-render. 

In our case, we should normalize the contributions with filters and options, so I am separating reducers accordingly than combining them in the `contributionScreen` reducer. However, the utility type `LOADABLE` will lose its effect as it is used in the contributions array for now, so I am thinking to put a new property called `state` in the `contributionReducer` that will be the value for it so what data type you may wanna use for it (`LOADABLE<?>`?)

**Pull request closed without merging**
