### PR TITLE
Chore: mobile folder tweaks + code style setup

### PR DESCRIPTION
**Pull request by ZibanPirate**
# Description

This PR adds rules to define code style for `./mobile` folder, and apply these rules to the existing code.

## Type of change

- Refactoring

### CODE REVIEW

**Comment by ZibanPirate** [comment]
hey @Omar-Belghaouti if you currently don't have a WIP code, please review and merge this PR first, then branch out from the up-to-date `main`, these are a bit important changes, they helps us write better code and let other contributors work easily with the code and ensures they don't write bad quality code

**Comment by Omar-Belghaouti** [comment]
> hey @Omar-Belghaouti if you currently don't have a WIP code, please review and merge this PR first, then branch out from the up-to-date `main`, these are a bit important changes, they helps us write better code and let other contributors work easily with the code and ensures they don't write bad quality code

I don't have a WIP code currently, so I'll review it rn

**Review by Omar-Belghaouti — APPROVED** [review]
Seems good, now we can have structured project as we can add code guidelines later on.

**Comment by ZibanPirate** [comment]
yup, we will eventually settle on a better code structure by the time, we're having a really good start so-far 👌🏽

**Pull request merged**
