### PR TITLE
fix-text-responsive-in-mobile

### PR DESCRIPTION
**Pull request by AmineVolk**
Use material-ui Typography component instead of div to use the right style in theme/typography.tsx
It'll also fix the displayed text in mobile

### CODE REVIEW

**Comment by ZibanPirate** [comment]
@AmineVolk we just pushed version 0.11.2 (your last PR was included) please take a pull from master branch, and fix the merge conflict

**Review by ZibanPirate — CHANGES_REQUESTED** [review]
@AmineVolk we just pushed version 0.11.2 (your last PR was included) please take a pull from master branch, and fix the merge conflict

**Comment by AmineVolk** [comment]
> please take

okey no problem

**Comment by AmineVolk** [comment]
@ZibanPirate no need to manage the fixes have been fixed in the new version

**Comment by ZibanPirate** [comment]
Great then, thanks for your efforts !

closing as there are no further actions to be done

**Pull request closed without merging**
