### PR TITLE
Add new GitHub Controller

### PR DESCRIPTION
**Pull request by well-balanced**
# Description
Related issue #277 and also PR #283

implementing below
> Migrate all old endpoints to /v2 and update frontend accordingly

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by well-balanced** [comment]
I just created this PR for feedback. if I get feedback from the member, this PR gonna be closed.

I have some questions
- are all endpoints gonna return DTO objects like a `GetContributorsResponseDto` ?
- I handled errors in the `GithubService`'s method using `try` `catch`. 
if you don't like it can you suggest to me another best practice?
- in this migration case, the old api just returns GitHub API's response. Do I have to make Dto object like a `GithubUserDto`?

please give me a feedback thx 🙏

**Comment by ZibanPirate** [comment]
thank you @well-balanced for your PR !

Answering your questions:
> * are all endpoints gonna return DTO objects like a `GetContributorsResponseDto` ?

Yes, basically we need two things for typing an endpoint:
- first, the return type; an interface to strongly type our controller.
- second, the return DTO class, which is needed for OpenApi and swagger to generate automatic documentation for `/v2/docs` route.
so, instead of doing each one separately, we just create a DTO class that also act as a return type, so two birds in one stone, while we apply the DRY principle.

> * I handled errors in the `GithubService`'s method using `try` `catch`.
>   if you don't like it can you suggest to me another best practice?

Error should be thrown, don't use try catch, as we have an error handler in [error.ts](https://github.com/dzcode-io/dzcode.io/blob/main/api/src/app/middlewares/error.ts)

> * in this migration case, the old api just returns GitHub API's response. Do I have to make Dto object like a `GithubUserDto`?
> 
> please give me a feedback thx 🙏

So, unlike the controller endpoint, calling third party APIs like Github, doesn't need to be documented,however the axios response definitely need to be strongly typed, so.., we just need a regular typescript interface/type here ;)

> I just created this PR for feedback. if I get feedback from the member, this PR gonna be closed.

As for this PR, we can merge it, we just need some small changes, no need to waste your effort by closing it ;)
i will give you some feedback on the PR itslef, once fixed we can merge!

**Comment by well-balanced** [comment]
I fixed some parts
- Delete try catch expression
- Add GitHub repo API Response interface into `types.ts`

Could you feedback to me again specifically?

**Comment by ZibanPirate** [comment]
well, since you already worked on #286 and merged both #290 and #289 , i believe there is no point in leaving this open, so closing ...
if you want to re-open it again, feel free to do so @well-balanced , and again thank you so much for your contribution!

**Pull request closed without merging**
