### PR TITLE
Feature: Implementing contribute screen on mobile app

### PR DESCRIPTION
**Pull request by Omar-Belghaouti**
# Description

This feature is dedicated for implementing the contribute screen in the mobile app.

## Tasks
- [x]  Getting contributions.
- [x]  Displaying contributions.
- [x]  Filtering contributions.

## Type of change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Omar-Belghaouti** [comment]
I'd also want to have some empty state svgs or lottie files if there is any to apply them when no contributions are not found.

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate I need your opinion on this one, should the filters be updated when checking one of them after getting the result? Like what happens in the website ? or should I not updated them and leave them as the initial state or when pulling to refresh the contributions?

**Review by ZibanPirate — APPROVED** [review]
really awesome work @Omar-Belghaouti i learned new stuff from this code 🙏🏽

i feel like this PR can be merged now, the feedback can be addressed as followup PRs, if you feel like it too then just fix the conflict and merge ✅


couple of notes on the code, which we will address as separate follow-up PRs:
- we can move the `calculate-date.ts` file to `./common` folder, then reuse it on both `./web` and `./mobile` folders cuz it's also on the web as `./web/src/common/utils/elapsed-time.ts`
- there's no need to re-create the response interfaces, instead we can `import` them `from "src/.common/types/api-responses"`
- We need to use Redux, this will make dev easier and predictable. (this will also make the filters work properly)
- maybe add some margin at the bottom of the cards container, so that last results will not appear at the very bottom.
- maybe we can place the filters component inside a `FAB.Group` component so it appears just like the mobile version of the website?
- and Yes, we probably should show something when there's an empty result.

**Comment by ZibanPirate** [comment]
> @ZibanPirate I need your opinion on this one, should the filters be updated when checking one of them after getting the result? Like what happens in the website ? or should I not updated them and leave them as the initial state or when pulling to refresh the contributions?

good question, we should follow the website where:
- filter options are dictated by the api response.
- the state of each filter option however (check or not) should be preserved if the filter option is still there.
- when clicking on a filter option, it should add to the already selected filter options, so we would be able to select multiple options.
- when clicking on a Chip (label's on the card) however, we should reset the filters states and select only that option.

this may be challenging with the useState, but it will be piece of cake when using redux, so i suggest we address this as followup PR after we implement redux.

**Comment by Omar-Belghaouti** [comment]
> > @ZibanPirate I need your opinion on this one, should the filters be updated when checking one of them after getting the result? Like what happens in the website ? or should I not updated them and leave them as the initial state or when pulling to refresh the contributions?
> 
> good question, we should follow the website where:
> 
> * filter options are dictated by the api response.
> * the state of each filter option however (check or not) should be preserved if the filter option is still there.
> * when clicking on a filter option, it should add to the already selected filter options, so we would be able to select multiple options.
> * when clicking on a Chip (label's on the card) however, we should reset the filters states and select only that option.
> 
> this may be challenging with the useState, but it will be piece of cake when using redux, so i suggest we address this as followup PR after we implement redux.

You can say that I already implemented the half of those points. in each filters state change I am getting again the response from the api. when clicking the chip the filters are reset, but when checking a filter the response will change the filters as well, as the case for the web. and when pull to refresh it will reset all filters to the initial state, so that way it would give the initial result if the user want it. 

There is something else @ZibanPirate  and that's the empty state, should we do some custom image or lottie file or what?

**Comment by Omar-Belghaouti** [comment]
> > @ZibanPirate I need your opinion on this one, should the filters be updated when checking one of them after getting the result? Like what happens in the website ? or should I not updated them and leave them as the initial state or when pulling to refresh the contributions?
> 
> good question, we should follow the website where:
> 
> * filter options are dictated by the api response.
> * the state of each filter option however (check or not) should be preserved if the filter option is still there.
> * when clicking on a filter option, it should add to the already selected filter options, so we would be able to select multiple options.
> * when clicking on a Chip (label's on the card) however, we should reset the filters states and select only that option.
> 
> this may be challenging with the useState, but it will be piece of cake when using redux, so i suggest we address this as followup PR after we implement redux.

I will do these changes on this PR

**Pull request merged**
